#!/bin/bash
# Multiple, chained, self-compilation runs.
# Run this every time you change the crap.crap source
# This ougut to test it.
./crap crap.crap \
| tcc -I./include -L./lib -lreg -run - crap.crap \
| tcc -I./include -L./lib -lreg -run - crap.crap \
| tcc -I./include -L./lib -lreg -run - "$@"
