#!/bin/bash
# Multiple, chained, self-compilation runs.
# Run this after modifying the crap.crap source
# This ougut to test it.
./crap crap.crap \
| tcc -Iinclude -Llib lib/*.o -run - crap.crap \
| tcc -Iinclude -Llib lib/*.o -run - crap.crap \
| tcc -Iinclude -Llib lib/*.o -run - "$@"
