#!/bin/bash
#
# Begin crap scripts with the following line
# #!crapper [compiler args] -- [program args]
#
# Don't forget to make them executable with chmod +x!
#
# Scripts that supply their own [program args] are redundant, yes.
# We do it because we can.
#
# Copyright (C) 2018-2024 Henry Kroll III, https://thenerdshow.com
# Some permissions granted with included GPL-2 LICENSE
# NO WARRANTEE

# get position of needle in haystack
pos() {
    c=0; local hay needle=$1
    shift
    for hay; do
        if [[ $hay == $needle ]]; then echo $c; return 0;fi
    ((c++))
    done; return 1
}

ax=($(echo "$1"|xargs)) #unquote shebang arguments ~_^

# split args on --, into left and right tokens
left=(); right=()
p=$(pos "--" "${ax[@]}")
if [[ $p > 0 ]]; then
    left="${ax[@]:0:$p}"
    right="${ax[@]:$p+1}"
fi

# run it
crap "${@:(-1)}" | tcc ${left[@]} -run - ${right[@]}
